// Generated from COC7 空白卡「附表」B95:K212.
// Do not edit by hand unless you update the source card.
import type { Skill } from "../schema";

export const COC7_EXTRA_SKILLS: readonly Skill[] = [
  { id: "射击（冲锋枪）", name: "射击（冲锋枪）", category: "COMBAT", base: "15" },
  { id: "射击（喷射器）", name: "射击（喷射器）", category: "COMBAT", base: "10" },
  { id: "射击（机枪）", name: "射击（机枪）", category: "COMBAT", base: "10" },
  { id: "射击（重武器）", name: "射击（重武器）", category: "COMBAT", base: "10" },
  { id: "格斗（剑）", name: "格斗（剑）", category: "COMBAT", base: "20" },
  { id: "格斗（电锯）", name: "格斗（电锯）", category: "COMBAT", base: "10" },
  { id: "格斗（矛）", name: "格斗（矛）", category: "COMBAT", base: "20" },
  { id: "格斗（绞具）", name: "格斗（绞具）", category: "COMBAT", base: "15" },
  { id: "格斗（链枷）", name: "格斗（链枷）", category: "COMBAT", base: "10" },
  { id: "格斗（鞭子）", name: "格斗（鞭子）", category: "COMBAT", base: "5" },
  { id: "炮术", name: "炮术", category: "COMBAT", base: "1" },
  { id: "动物学", name: "动物学", category: "KNOWLEDGE", base: "1" },
  { id: "化学", name: "化学", category: "KNOWLEDGE", base: "1" },
  { id: "司法科学", name: "司法科学", category: "KNOWLEDGE", base: "1" },
  { id: "地质学", name: "地质学", category: "KNOWLEDGE", base: "1" },
  { id: "天文学", name: "天文学", category: "KNOWLEDGE", base: "1" },
  { id: "密码学", name: "密码学", category: "KNOWLEDGE", base: "1" },
  { id: "工程学", name: "工程学", category: "KNOWLEDGE", base: "1" },
  { id: "数学", name: "数学", category: "KNOWLEDGE", base: "10" },
  { id: "植物学", name: "植物学", category: "KNOWLEDGE", base: "1" },
  { id: "气象学", name: "气象学", category: "KNOWLEDGE", base: "1" },
  { id: "物理学", name: "物理学", category: "KNOWLEDGE", base: "1" },
  { id: "生物学", name: "生物学", category: "KNOWLEDGE", base: "1" },
  { id: "药学", name: "药学", category: "KNOWLEDGE", base: "1" },
  { id: "学问", name: "学问", category: "OTHER", base: "1" },
  { id: "技艺（乐理）", name: "技艺（乐理）", category: "OTHER", base: "5" },
  { id: "技艺（书法）", name: "技艺（书法）", category: "OTHER", base: "5" },
  { id: "技艺（伪造）", name: "技艺（伪造）", category: "OTHER", base: "5" },
  { id: "技艺（制陶）", name: "技艺（制陶）", category: "OTHER", base: "5" },
  { id: "技艺（厨艺）", name: "技艺（厨艺）", category: "OTHER", base: "5" },
  { id: "技艺（吹制玻璃管）", name: "技艺（吹制玻璃管）", category: "OTHER", base: "5" },
  { id: "技艺（建筑）", name: "技艺（建筑）", category: "OTHER", base: "5" },
  { id: "技艺（打字）", name: "技艺（打字）", category: "OTHER", base: "5" },
  { id: "技艺（技术制图）", name: "技艺（技术制图）", category: "OTHER", base: "5" },
  { id: "技艺（捕鱼）", name: "技艺（捕鱼）", category: "OTHER", base: "5" },
  { id: "技艺（摄影）", name: "技艺（摄影）", category: "OTHER", base: "5" },
  { id: "技艺（文学）", name: "技艺（文学）", category: "OTHER", base: "5" },
  { id: "技艺（木匠）", name: "技艺（木匠）", category: "OTHER", base: "5" },
  { id: "技艺（杂技）", name: "技艺（杂技）", category: "OTHER", base: "5" },
  { id: "技艺（歌剧歌唱）", name: "技艺（歌剧歌唱）", category: "OTHER", base: "5" },
  { id: "技艺（歌唱）", name: "技艺（歌唱）", category: "OTHER", base: "5" },
  { id: "技艺（理发）", name: "技艺（理发）", category: "OTHER", base: "5" },
  { id: "技艺（粉刷匠与油漆工）", name: "技艺（粉刷匠与油漆工）", category: "OTHER", base: "5" },
  { id: "技艺（美术）", name: "技艺（美术）", category: "OTHER", base: "5" },
  { id: "技艺（耕作）", name: "技艺（耕作）", category: "OTHER", base: "5" },
  { id: "技艺（舞蹈）", name: "技艺（舞蹈）", category: "OTHER", base: "5" },
  { id: "技艺（莫里斯舞）", name: "技艺（莫里斯舞）", category: "OTHER", base: "5" },
  { id: "技艺（表演）", name: "技艺（表演）", category: "OTHER", base: "5" },
  { id: "技艺（裁缝）", name: "技艺（裁缝）", category: "OTHER", base: "5" },
  { id: "技艺（速记）", name: "技艺（速记）", category: "OTHER", base: "5" },
  { id: "技艺（酿酒）", name: "技艺（酿酒）", category: "OTHER", base: "5" },
  { id: "技艺（雕塑）", name: "技艺（雕塑）", category: "OTHER", base: "5" },
  { id: "技艺（风水）", name: "技艺（风水）", category: "OTHER", base: "5" },
  { id: "催眠", name: "催眠", category: "PHYSICAL", base: "1" },
  { id: "潜水", name: "潜水", category: "PHYSICAL", base: "1" },
  { id: "爆破", name: "爆破", category: "PHYSICAL", base: "1" },
  { id: "读唇", name: "读唇", category: "PHYSICAL", base: "1" },
  { id: "驯兽", name: "驯兽", category: "PHYSICAL", base: "5" },
  { id: "驾驶", name: "驾驶", category: "PHYSICAL", base: "1" },
];
